### ISSUE TITLE
graph heuristic search not working

### ISSUE THREAD

**Issue by shara-cell** [allanzhao/RoboGrammar#13]
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given

I always get the above mentioned error when i try running graph heuristic search. any suggestions to correct it?

**Comment by eanswer** [comment]
could you elaborate more about the error, maybe screenshot it?

**Comment by rainingDesert** [comment]
I also get this error. I think it might be caused by DenseSAGEConv under different versions of torch_geometric. Under torch_geometric 1.4.3, the forward function is defined as "forward(self, x, adj, mask=None, add_loop=True)". But in the latest version, it is modified to be "forward(self, x, adj, mask=None)". But I am also wondering whether it is safe to directly use the latest version?

**Comment by eanswer** [comment]
I see! yes, you should be able to directly use the latest version.

**Comment by allanzhao** [comment]
I made some (not fully tested) modifications to add the loops ourselves, since they aren't supported in Torch Geometric anymore. This way it should work with both the old and new versions.
